// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/auth/login.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/login/index.tsx";
import * as $$0 from "./islands/LoginForm.tsx";
import * as $$1 from "./islands/ProtectedRoute.tsx";
import * as $$2 from "./islands/ToggledMenu.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/auth/login.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/login/index.tsx": $4,
  },
  islands: {
    "./islands/LoginForm.tsx": $$0,
    "./islands/ProtectedRoute.tsx": $$1,
    "./islands/ToggledMenu.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
